
package edu.sado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "IntegrationSystem_IntegrationService", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegrationSystemIntegrationService {


    /**
     *
     * @param profileId
     * @param cardId
     * @param stateId
     * @param operationId
     * @param userId
     * @throws IntegrationSystemIntegrationServiceCheckAccessForOperationSecurityExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CheckAccessForOperation", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CheckAccessForOperation")
    @RequestWrapper(localName = "CheckAccessForOperation", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CheckAccessForOperation")
    @ResponseWrapper(localName = "CheckAccessForOperationResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CheckAccessForOperationResponse")
    public void checkAccessForOperation(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "cardId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String cardId,
            @WebParam(name = "operationId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String operationId,
            @WebParam(name = "stateId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String stateId,
            @WebParam(name = "userId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String userId)
        throws IntegrationSystemIntegrationServiceCheckAccessForOperationSecurityExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param searchQuery
     * @param folderId
     * @return
     *     returns edu.sado.ArrayOfGuid
     * @throws IntegrationSystemIntegrationServiceGetFolderContentFolderOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetFolderContent", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetFolderContent")
    @WebResult(name = "GetFolderContentResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetFolderContent", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetFolderContent")
    @ResponseWrapper(localName = "GetFolderContentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetFolderContentResponse")
    public ArrayOfGuid getFolderContent(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "folderId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String folderId,
            @WebParam(name = "searchQuery", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    SearchQuery searchQuery)
        throws IntegrationSystemIntegrationServiceGetFolderContentFolderOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param cardId
     * @param stateId
     * @param userId
     * @return
     *     returns edu.sado.ArrayOfOperation
     * @throws IntegrationSystemIntegrationServiceGetAccessOperationsSecurityExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccessOperations", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetAccessOperations")
    @WebResult(name = "GetAccessOperationsResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetAccessOperations", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetAccessOperations")
    @ResponseWrapper(localName = "GetAccessOperationsResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetAccessOperationsResponse")
    public ArrayOfOperation getAccessOperations(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "cardId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String cardId,
            @WebParam(name = "stateId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String stateId,
            @WebParam(name = "userId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String userId)
        throws IntegrationSystemIntegrationServiceGetAccessOperationsSecurityExceptionFaultFaultMessage
    ;

    /**
     *
     * @param reportId
     * @param profileId
     * @param arguments
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceExecuteReportMethodExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ExecuteReport", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/ExecuteReport")
    @WebResult(name = "ExecuteReportResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "ExecuteReport", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteReport")
    @ResponseWrapper(localName = "ExecuteReportResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteReportResponse")
    public String executeReport(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "reportId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String reportId,
            @WebParam(name = "arguments", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    ArrayOfMethodArgument arguments)
        throws IntegrationSystemIntegrationServiceExecuteReportMethodExceptionFaultFaultMessage
    ;

    /**
     *
     * @param regCardId
     * @return
     *     returns boolean
     * @throws IntegrationSystemIntegrationServiceCheckDocumentProtectStateDocsProtectionNotInstalledExceptionFaultFaultMessage
     * @throws IntegrationSystemIntegrationServiceCheckDocumentProtectStateSecurityExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CheckDocumentProtectState", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CheckDocumentProtectState")
    @WebResult(name = "CheckDocumentProtectStateResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "CheckDocumentProtectState", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CheckDocumentProtectState")
    @ResponseWrapper(localName = "CheckDocumentProtectStateResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CheckDocumentProtectStateResponse")
    public boolean checkDocumentProtectState(
            @WebParam(name = "regCardId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String regCardId)
        throws IntegrationSystemIntegrationServiceCheckDocumentProtectStateDocsProtectionNotInstalledExceptionFaultFaultMessage, IntegrationSystemIntegrationServiceCheckDocumentProtectStateSecurityExceptionFaultFaultMessage
    ;

    /**
     *
     * @param resourceId
     * @param operationId
     * @param typeId
     * @param message
     * @param userId
     * @param parentId
     * @throws IntegrationSystemIntegrationServiceCreateApplicationLogRecordMethodExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateApplicationLogRecord", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CreateApplicationLogRecord")
    @RequestWrapper(localName = "CreateApplicationLogRecord", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateApplicationLogRecord")
    @ResponseWrapper(localName = "CreateApplicationLogRecordResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateApplicationLogRecordResponse")
    public void createApplicationLogRecord(
            @WebParam(name = "message", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String message,
            @WebParam(name = "typeId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String typeId,
            @WebParam(name = "resourceId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String resourceId,
            @WebParam(name = "operationId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String operationId,
            @WebParam(name = "userId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String userId,
            @WebParam(name = "parentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String parentId)
        throws IntegrationSystemIntegrationServiceCreateApplicationLogRecordMethodExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param employeeId
     * @return
     *     returns edu.sado.Employee
     * @throws IntegrationSystemIntegrationServiceGetCounterpartyEmployeeObjectNotFoundExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCounterpartyEmployee", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetCounterpartyEmployee")
    @WebResult(name = "GetCounterpartyEmployeeResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetCounterpartyEmployee", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetCounterpartyEmployee")
    @ResponseWrapper(localName = "GetCounterpartyEmployeeResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetCounterpartyEmployeeResponse")
    public Employee getCounterpartyEmployee(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "employeeId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String employeeId)
        throws IntegrationSystemIntegrationServiceGetCounterpartyEmployeeObjectNotFoundExceptionFaultFaultMessage
    ;

    /**
     *
     * @param companyId
     * @param profileId
     * @return
     *     returns edu.sado.Company
     * @throws IntegrationSystemIntegrationServiceGetCounterpartyCompanyObjectNotFoundExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCounterpartyCompany", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetCounterpartyCompany")
    @WebResult(name = "GetCounterpartyCompanyResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetCounterpartyCompany", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetCounterpartyCompany")
    @ResponseWrapper(localName = "GetCounterpartyCompanyResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetCounterpartyCompanyResponse")
    public Company getCounterpartyCompany(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "companyId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String companyId)
        throws IntegrationSystemIntegrationServiceGetCounterpartyCompanyObjectNotFoundExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param name
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceGetOrganizationIdObjectNotFoundExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetOrganizationId", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetOrganizationId")
    @WebResult(name = "GetOrganizationIdResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetOrganizationId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetOrganizationId")
    @ResponseWrapper(localName = "GetOrganizationIdResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetOrganizationIdResponse")
    public String getOrganizationId(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "name", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String name)
        throws IntegrationSystemIntegrationServiceGetOrganizationIdObjectNotFoundExceptionFaultFaultMessage
    ;

    /**
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Test", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/Test")
    @WebResult(name = "TestResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "Test", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.TestResponse")
    public String test();

    /**
     *
     * @param profileId
     * @param searchQuery
     * @return
     *     returns edu.sado.ArrayOfGuid
     * @throws IntegrationSystemIntegrationServiceGetSearchResultSearchExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSearchResult", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetSearchResult")
    @WebResult(name = "GetSearchResultResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetSearchResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetSearchResult")
    @ResponseWrapper(localName = "GetSearchResultResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetSearchResultResponse")
    public ArrayOfGuid getSearchResult(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "searchQuery", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    SearchQuery searchQuery)
        throws IntegrationSystemIntegrationServiceGetSearchResultSearchExceptionFaultFaultMessage
    ;

    /**
     *
     * @param document
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceCreateDocumentDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CreateDocument")
    @WebResult(name = "CreateDocumentResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "CreateDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateDocument")
    @ResponseWrapper(localName = "CreateDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateDocumentResponse")
    public String createDocument(
            @WebParam(name = "document", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    DocumentItem document)
        throws IntegrationSystemIntegrationServiceCreateDocumentDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param task
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceCreateTaskDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateTask", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CreateTask")
    @WebResult(name = "CreateTaskResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "CreateTask", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateTask")
    @ResponseWrapper(localName = "CreateTaskResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateTaskResponse")
    public String createTask(
            @WebParam(name = "task", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    DocumentItem task)
        throws IntegrationSystemIntegrationServiceCreateTaskDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param files
     * @param id
     * @throws IntegrationSystemIntegrationServiceAddFilesToDocumentDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddFilesToDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/AddFilesToDocument")
    @RequestWrapper(localName = "AddFilesToDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddFilesToDocument")
    @ResponseWrapper(localName = "AddFilesToDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddFilesToDocumentResponse")
    public void addFilesToDocument(
            @WebParam(name = "id", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String id,
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "files", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FilesItem files)
        throws IntegrationSystemIntegrationServiceAddFilesToDocumentDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param file
     * @param profileId
     * @param id
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceAddFileToDocumentDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddFileToDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/AddFileToDocument")
    @WebResult(name = "AddFileToDocumentResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "AddFileToDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddFileToDocument")
    @ResponseWrapper(localName = "AddFileToDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddFileToDocumentResponse")
    public String addFileToDocument(
            @WebParam(name = "id", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String id,
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "file", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FileItem file)
        throws IntegrationSystemIntegrationServiceAddFileToDocumentDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param cardFileId
     * @param addFileToDocumentExResult
     * @param file
     * @param profileId
     * @param id
     * @throws IntegrationSystemIntegrationServiceAddFileToDocumentExDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddFileToDocumentEx", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/AddFileToDocumentEx")
    @RequestWrapper(localName = "AddFileToDocumentEx", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddFileToDocumentEx")
    @ResponseWrapper(localName = "AddFileToDocumentExResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddFileToDocumentExResponse")
    public void addFileToDocumentEx(
            @WebParam(name = "id", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String id,
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "file", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FileItem file,
            @WebParam(name = "AddFileToDocumentExResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", mode = WebParam.Mode.OUT)
                    Holder<String> addFileToDocumentExResult,
            @WebParam(name = "cardFileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", mode = WebParam.Mode.OUT)
                    Holder<String> cardFileId)
        throws IntegrationSystemIntegrationServiceAddFileToDocumentExDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param file
     * @param profileId
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceCreateCardFileFileOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateCardFile", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CreateCardFile")
    @WebResult(name = "CreateCardFileResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "CreateCardFile", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateCardFile")
    @ResponseWrapper(localName = "CreateCardFileResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateCardFileResponse")
    public String createCardFile(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "file", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FileItem file)
        throws IntegrationSystemIntegrationServiceCreateCardFileFileOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param notification
     * @throws IntegrationSystemIntegrationServiceAddNotificationRecordDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddNotificationRecord", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/AddNotificationRecord")
    @RequestWrapper(localName = "AddNotificationRecord", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddNotificationRecord")
    @ResponseWrapper(localName = "AddNotificationRecordResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddNotificationRecordResponse")
    public void addNotificationRecord(
            @WebParam(name = "notification", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    NotificationItem notification)
        throws IntegrationSystemIntegrationServiceAddNotificationRecordDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param signature
     * @param profileId
     * @param fileId
     * @throws IntegrationSystemIntegrationServiceAddSignatureToFileFileOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddSignatureToFile", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/AddSignatureToFile")
    @RequestWrapper(localName = "AddSignatureToFile", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddSignatureToFile")
    @ResponseWrapper(localName = "AddSignatureToFileResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddSignatureToFileResponse")
    public void addSignatureToFile(
            @WebParam(name = "fileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String fileId,
            @WebParam(name = "signature", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FileSignature signature,
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId)
        throws IntegrationSystemIntegrationServiceAddSignatureToFileFileOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param cardFileId
     * @param signature
     * @param profileId
     * @throws IntegrationSystemIntegrationServiceAddSignatureToCardFileFileOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddSignatureToCardFile", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/AddSignatureToCardFile")
    @RequestWrapper(localName = "AddSignatureToCardFile", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddSignatureToCardFile")
    @ResponseWrapper(localName = "AddSignatureToCardFileResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddSignatureToCardFileResponse")
    public void addSignatureToCardFile(
            @WebParam(name = "cardFileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String cardFileId,
            @WebParam(name = "signature", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FileSignature signature,
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId)
        throws IntegrationSystemIntegrationServiceAddSignatureToCardFileFileOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param fileId
     * @return
     *     returns edu.sado.ArrayOfFileSignature
     * @throws IntegrationSystemIntegrationServiceGetFileSignaturesFileOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetFileSignatures", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetFileSignatures")
    @WebResult(name = "GetFileSignaturesResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetFileSignatures", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetFileSignatures")
    @ResponseWrapper(localName = "GetFileSignaturesResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetFileSignaturesResponse")
    public ArrayOfFileSignature getFileSignatures(
            @WebParam(name = "fileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String fileId,
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId)
        throws IntegrationSystemIntegrationServiceGetFileSignaturesFileOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param documentId
     * @return
     *     returns edu.sado.DocumentItem
     * @throws IntegrationSystemIntegrationServiceGetDocumentDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetDocument")
    @WebResult(name = "GetDocumentResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocument")
    @ResponseWrapper(localName = "GetDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocumentResponse")
    public DocumentItem getDocument(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId)
        throws IntegrationSystemIntegrationServiceGetDocumentDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param taskId
     * @return
     *     returns edu.sado.DocumentItem
     * @throws IntegrationSystemIntegrationServiceGetTaskDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetTask", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetTask")
    @WebResult(name = "GetTaskResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetTask", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetTask")
    @ResponseWrapper(localName = "GetTaskResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetTaskResponse")
    public DocumentItem getTask(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "taskId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String taskId)
        throws IntegrationSystemIntegrationServiceGetTaskDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param documentId
     * @return
     *     returns edu.sado.FilesItem
     * @throws IntegrationSystemIntegrationServiceGetDocumentFilesDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDocumentFiles", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetDocumentFiles")
    @WebResult(name = "GetDocumentFilesResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetDocumentFiles", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocumentFiles")
    @ResponseWrapper(localName = "GetDocumentFilesResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocumentFilesResponse")
    public FilesItem getDocumentFiles(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId)
        throws IntegrationSystemIntegrationServiceGetDocumentFilesDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param documentId
     * @param fileId
     * @return
     *     returns edu.sado.FileItem
     * @throws IntegrationSystemIntegrationServiceGetDocumentFileDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDocumentFile", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetDocumentFile")
    @WebResult(name = "GetDocumentFileResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetDocumentFile", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocumentFile")
    @ResponseWrapper(localName = "GetDocumentFileResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocumentFileResponse")
    public FileItem getDocumentFile(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId,
            @WebParam(name = "fileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String fileId)
        throws IntegrationSystemIntegrationServiceGetDocumentFileDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param cardFileId
     * @param profileId
     * @return
     *     returns edu.sado.FileItem
     * @throws IntegrationSystemIntegrationServiceGetFileFromCardFileFileOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetFileFromCardFile", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetFileFromCardFile")
    @WebResult(name = "GetFileFromCardFileResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetFileFromCardFile", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetFileFromCardFile")
    @ResponseWrapper(localName = "GetFileFromCardFileResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetFileFromCardFileResponse")
    public FileItem getFileFromCardFile(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "cardFileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String cardFileId)
        throws IntegrationSystemIntegrationServiceGetFileFromCardFileFileOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param notificationStatus
     * @throws IntegrationSystemIntegrationServiceUpdateNotificationStatusDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateNotificationStatus", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/UpdateNotificationStatus")
    @RequestWrapper(localName = "UpdateNotificationStatus", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateNotificationStatus")
    @ResponseWrapper(localName = "UpdateNotificationStatusResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateNotificationStatusResponse")
    public void updateNotificationStatus(
            @WebParam(name = "notificationStatus", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    NotificationItem notificationStatus)
        throws IntegrationSystemIntegrationServiceUpdateNotificationStatusDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param task
     * @throws IntegrationSystemIntegrationServiceUpdateDocumentDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/UpdateDocument")
    @RequestWrapper(localName = "UpdateDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateDocument")
    @ResponseWrapper(localName = "UpdateDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateDocumentResponse")
    public void updateDocument(
            @WebParam(name = "task", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    DocumentItem task)
        throws IntegrationSystemIntegrationServiceUpdateDocumentDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param document
     * @throws IntegrationSystemIntegrationServiceUpdateTaskDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateTask", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/UpdateTask")
    @RequestWrapper(localName = "UpdateTask", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateTask")
    @ResponseWrapper(localName = "UpdateTaskResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateTaskResponse")
    public void updateTask(
            @WebParam(name = "document", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    DocumentItem document)
        throws IntegrationSystemIntegrationServiceUpdateTaskDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param document
     * @param files
     */
    @WebMethod(operationName = "UpdateFilesInDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/UpdateFilesInDocument")
    @RequestWrapper(localName = "UpdateFilesInDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateFilesInDocument")
    @ResponseWrapper(localName = "UpdateFilesInDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateFilesInDocumentResponse")
    public void updateFilesInDocument(
            @WebParam(name = "document", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    DocumentItem document,
            @WebParam(name = "files", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FilesItem files);

    /**
     *
     * @param profileId
     * @param files
     * @param id
     */
    @WebMethod(operationName = "UpdateFileInDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/UpdateFileInDocument")
    @RequestWrapper(localName = "UpdateFileInDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateFileInDocument")
    @ResponseWrapper(localName = "UpdateFileInDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.UpdateFileInDocumentResponse")
    public void updateFileInDocument(
            @WebParam(name = "id", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String id,
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "files", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FileItem files);

    /**
     *
     * @param profileid
     * @param employeeId
     * @return
     *     returns edu.sado.AddresseeExt
     * @throws IntegrationSystemIntegrationServiceGetEmployeeObjectNotFoundExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetEmployee", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetEmployee")
    @WebResult(name = "GetEmployeeResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetEmployee", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetEmployee")
    @ResponseWrapper(localName = "GetEmployeeResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetEmployeeResponse")
    public AddresseeExt getEmployee(
            @WebParam(name = "profileid", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileid,
            @WebParam(name = "employeeId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String employeeId)
        throws IntegrationSystemIntegrationServiceGetEmployeeObjectNotFoundExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param documentId
     * @param state
     * @throws IntegrationSystemIntegrationServiceChangeDocumentStateDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ChangeDocumentState", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/ChangeDocumentState")
    @RequestWrapper(localName = "ChangeDocumentState", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ChangeDocumentState")
    @ResponseWrapper(localName = "ChangeDocumentStateResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ChangeDocumentStateResponse")
    public void changeDocumentState(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId,
            @WebParam(name = "state", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    State state)
        throws IntegrationSystemIntegrationServiceChangeDocumentStateDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param destinationDocumentId
     * @param profileId
     * @param sourceDocumentId
     * @throws IntegrationSystemIntegrationServiceCreateLinkDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateLink", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CreateLink")
    @RequestWrapper(localName = "CreateLink", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateLink")
    @ResponseWrapper(localName = "CreateLinkResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateLinkResponse")
    public void createLink(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "sourceDocumentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String sourceDocumentId,
            @WebParam(name = "destinationDocumentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String destinationDocumentId)
        throws IntegrationSystemIntegrationServiceCreateLinkDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param destinationDocumentId
     * @param profileId
     * @param linkType
     * @param sourceDocumentId
     * @throws IntegrationSystemIntegrationServiceCreateLinkExDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateLinkEx", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CreateLinkEx")
    @RequestWrapper(localName = "CreateLinkEx", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateLinkEx")
    @ResponseWrapper(localName = "CreateLinkExResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateLinkExResponse")
    public void createLinkEx(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "sourceDocumentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String sourceDocumentId,
            @WebParam(name = "destinationDocumentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String destinationDocumentId,
            @WebParam(name = "linkType", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    LinkType linkType)
        throws IntegrationSystemIntegrationServiceCreateLinkExDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param documentId
     * @return
     *     returns edu.sado.DocumentItem
     * @throws IntegrationSystemIntegrationServiceGetDocumentInfoDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDocumentInfo", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetDocumentInfo")
    @WebResult(name = "GetDocumentInfoResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetDocumentInfo", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocumentInfo")
    @ResponseWrapper(localName = "GetDocumentInfoResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetDocumentInfoResponse")
    public DocumentItem getDocumentInfo(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId)
        throws IntegrationSystemIntegrationServiceGetDocumentInfoDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param query
     * @return
     *     returns edu.sado.ArrayOfAddresseeExt
     * @throws IntegrationSystemIntegrationServiceFindEmployeesSearchExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "FindEmployees", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/FindEmployees")
    @WebResult(name = "FindEmployeesResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "FindEmployees", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.FindEmployees")
    @ResponseWrapper(localName = "FindEmployeesResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.FindEmployeesResponse")
    public ArrayOfAddresseeExt findEmployees(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "query", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    EmployeeQuery query)
        throws IntegrationSystemIntegrationServiceFindEmployeesSearchExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param files
     * @param documentId
     * @param createApprovalCycleParams
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceCreateApprovalCycleDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateApprovalCycle", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/CreateApprovalCycle")
    @WebResult(name = "CreateApprovalCycleResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "CreateApprovalCycle", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateApprovalCycle")
    @ResponseWrapper(localName = "CreateApprovalCycleResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.CreateApprovalCycleResponse")
    public String createApprovalCycle(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId,
            @WebParam(name = "files", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    FilesItem files,
            @WebParam(name = "createApprovalCycleParams", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    CreateApprovalCycleParams createApprovalCycleParams)
        throws IntegrationSystemIntegrationServiceCreateApprovalCycleDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param documentId
     * @param startApprovalCycleParams
     * @throws IntegrationSystemIntegrationServiceStartApprovalCycleDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartApprovalCycle", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/StartApprovalCycle")
    @RequestWrapper(localName = "StartApprovalCycle", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.StartApprovalCycle")
    @ResponseWrapper(localName = "StartApprovalCycleResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.StartApprovalCycleResponse")
    public void startApprovalCycle(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId,
            @WebParam(name = "startApprovalCycleParams", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    StartApprovalCycleParams startApprovalCycleParams)
        throws IntegrationSystemIntegrationServiceStartApprovalCycleDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param resolutionId
     * @param profileId
     * @return
     *     returns edu.sado.DocumentItem
     * @throws IntegrationSystemIntegrationServiceGetResolutionDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetResolution", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetResolution")
    @WebResult(name = "GetResolutionResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetResolution", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetResolution")
    @ResponseWrapper(localName = "GetResolutionResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetResolutionResponse")
    public DocumentItem getResolution(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "resolutionId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String resolutionId)
        throws IntegrationSystemIntegrationServiceGetResolutionDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param query
     * @return
     *     returns edu.sado.ArrayOfQualifiedValue
     * @throws IntegrationSystemIntegrationServiceFindOrganisationsSearchExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "FindOrganisations", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/FindOrganisations")
    @WebResult(name = "FindOrganisationsResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "FindOrganisations", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.FindOrganisations")
    @ResponseWrapper(localName = "FindOrganisationsResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.FindOrganisationsResponse")
    public ArrayOfQualifiedValue findOrganisations(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "query", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    OrganisationQuery query)
        throws IntegrationSystemIntegrationServiceFindOrganisationsSearchExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param searchQuery
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceGetViewDataSearchExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetViewData", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/GetViewData")
    @WebResult(name = "GetViewDataResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "GetViewData", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetViewData")
    @ResponseWrapper(localName = "GetViewDataResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.GetViewDataResponse")
    public String getViewData(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "searchQuery", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    SearchQuery searchQuery)
        throws IntegrationSystemIntegrationServiceGetViewDataSearchExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param documentId
     * @param comment
     * @throws IntegrationSystemIntegrationServiceAddCommentToDocumentDocumentOperationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddCommentToDocument", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/AddCommentToDocument")
    @RequestWrapper(localName = "AddCommentToDocument", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddCommentToDocument")
    @ResponseWrapper(localName = "AddCommentToDocumentResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.AddCommentToDocumentResponse")
    public void addCommentToDocument(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "documentId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String documentId,
            @WebParam(name = "comment", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    Comment comment)
        throws IntegrationSystemIntegrationServiceAddCommentToDocumentDocumentOperationFaultFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param methodName
     * @param arguments
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceExecuteMethodMethodExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ExecuteMethod", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/ExecuteMethod")
    @WebResult(name = "ExecuteMethodResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "ExecuteMethod", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteMethod")
    @ResponseWrapper(localName = "ExecuteMethodResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteMethodResponse")
    public String executeMethod(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "methodName", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String methodName,
            @WebParam(name = "arguments", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    ArrayOfMethodArgument arguments)
        throws IntegrationSystemIntegrationServiceExecuteMethodMethodExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param operationId
     * @param arguments
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceExecuteMethodByIdMethodExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ExecuteMethodById", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/ExecuteMethodById")
    @WebResult(name = "ExecuteMethodByIdResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "ExecuteMethodById", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteMethodById")
    @ResponseWrapper(localName = "ExecuteMethodByIdResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteMethodByIdResponse")
    public String executeMethodById(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "operationId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String operationId,
            @WebParam(name = "arguments", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    ArrayOfMethodArgument arguments)
        throws IntegrationSystemIntegrationServiceExecuteMethodByIdMethodExceptionFaultFaultMessage
    ;

    /**
     *
     * @param profileId
     * @param methodName
     * @param arguments
     * @return
     *     returns java.lang.String
     * @throws IntegrationSystemIntegrationServiceExecuteReaderMethodMethodExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ExecuteReaderMethod", action = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService/IntegrationSystem_IntegrationService/ExecuteReaderMethod")
    @WebResult(name = "ExecuteReaderMethodResult", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
    @RequestWrapper(localName = "ExecuteReaderMethod", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteReaderMethod")
    @ResponseWrapper(localName = "ExecuteReaderMethodResponse", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService", className = "edu.sado.ExecuteReaderMethodResponse")
    public String executeReaderMethod(
            @WebParam(name = "profileId", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String profileId,
            @WebParam(name = "methodName", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    String methodName,
            @WebParam(name = "arguments", targetNamespace = "http://schemas.digdes.com/IntegrationSystem/2012/02/IntegrationService")
                    ArrayOfMethodArgument arguments)
        throws IntegrationSystemIntegrationServiceExecuteReaderMethodMethodExceptionFaultFaultMessage
    ;

}
